# Generated by Django 4.0.4 on 2023-05-05 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('companyName', models.CharField(max_length=50)),
                ('aboutCompany', models.TextField(max_length=1000)),
                ('contact', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.BigIntegerField()),
                ('experience', models.IntegerField()),
                ('qualifications', models.TextField(max_length=300)),
                ('responsibilities', models.TextField(max_length=2000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
